services:
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./web-client:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
